version: '3'

services:
  myDB:
    image: postgres:15.3
    container_name: redsocial
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=devstudios-redsocial
    volumes:
      - ./postgres:/var/lib/postgresql/data
